### ISSUE TITLE
pd-devs.org SSL issue

### ISSUE THREAD

**Issue by zhangyubaka** [PureDarwin/xnubuild#1]
It looks like pd-devs.org's certificate CN only include ww.pd-devs.org. If curl attempt to fetch https://pd-devs.org , it will raise a SSL error.

`curl: (51) SSL: no alternative certificate subject name matches target host name 'pd-devs.org'`

**Comment by csekel** [comment]
@zhangyubaka  Issue has been fixed in script
https://github.com/PureDarwin/xnubuild/commit/81e1b8848df2764638bf0354869a66173f551720

**Comment by probonopd** [comment]
...and please make it "Devs" rather than "Dev's" :)

**Comment by csekel** [comment]
will do you should sign up too

**Comment by probonopd** [comment]
Can't we log in using GitHub credentials?

**Comment by csekel** [comment]
I will be enabling OAuth once I get home.

**Comment by csekel** [comment]
all set @probonopd check it out!
